#!/usr/bin/env python

import argparse
import os
import shutil
import sys
import process_image
from PIL import Image

# command line arguments
parser = argparse.ArgumentParser(description='Normalize all .jpg images in a folder to be square')
parser.add_argument('-p', action='store', dest='path', help='root path containing all images', required=True)
parser.add_argument('-l', action='store', dest='length', type=int, help='the size in pixels of the desired square', default=150)

opts = parser.parse_args()

for (dirpath, dirnames, filenames) in os.walk(opts.path):
    for filename in filenames:
	image = Image.open(os.path.join(dirpath, filename))
	resized_image = process_image.resize_img(image, opts.length)
	resized_image.save(os.path.join(dirpath, filename))
